services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: accidents_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - APP_ENV=docker
      - DUCKDB_PATH=/app/data/warehouse/accidents.duckdb
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.streamlit
    container_name: accidents_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - APP_ENV=docker
      - DUCKDB_PATH=/app/data/warehouse/accidents.duckdb
    depends_on:
      - api
    restart: unless-stopped

  pipeline:
    build:
      context: .
      dockerfile: docker/Dockerfile.pipeline
    container_name: accidents_pipeline
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - APP_ENV=docker
      - DUCKDB_PATH=/app/data/warehouse/accidents.duckdb
    profiles: ["jobs"]   # exécuté à la demande : docker compose run pipeline

  airflow:
    image: apache/airflow:2.9.1-python3.11
    container_name: accidents_airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - PYTHONPATH=/opt/airflow/project
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - .:/opt/airflow/project
    command: standalone
    profiles: ["airflow"]
